# DokerFile for FireDetectorAlarmDevice Microservice
FROM python:3.8-alpine

COPY . /microservice
COPY ../../src /src
COPY ../../requirements.txt .

RUN pip3 install -r requirements.txt

WORKDIR /microservice

CMD ["python3", "./FireButtonCreator.py"]